AY2223S1-CS2103T-T11-2/tp

- README.md
Add my personal photo for the AboutUs page
> Add aboutus photo

- docs/UserGuide.md
> Fix user guide issues

- docs/DeveloperGuide.md
- docs/team/johnrhimawan.md
Add skeletal Project Portfolio Page (PPP) for johnrhimawan
> Add Project Portfolio Page for John

- docs/DeveloperGuide.md
Add Non-Functional Requirements (NFR) and Glossary to Developer Guide
> Add NFR and Glossary to DG

- src/main/java/seedu/address/logic/commands/AddCommand.java
- src/main/java/seedu/address/logic/commands/EditCommand.java
- src/main/java/seedu/address/logic/parser/AddCommandParser.java
- src/main/java/seedu/address/logic/parser/CliSyntax.java
- src/main/java/seedu/address/logic/parser/EditCommandParser.java
- src/main/java/seedu/address/logic/parser/ParserUtil.java
- src/main/java/seedu/address/model/internship/Address.java
- src/main/java/seedu/address/model/internship/Internship.java
- src/main/java/seedu/address/model/internship/Status.java
- src/main/java/seedu/address/model/util/SampleDataUtil.java
- src/main/java/seedu/address/storage/JsonAdaptedInternship.java
- src/main/java/seedu/address/ui/InternshipCard.java
- src/main/resources/view/InternshipListCard.fxml
- src/test/data/JsonAddressBookStorageTest/invalidAndValidInternshipAddressBook.json
- src/test/data/JsonAddressBookStorageTest/invalidInternshipAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/duplicateInternshipAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/invalidInternshipAddressBook.json
- src/test/data/JsonSerializableAddressBookTest/typicalInternshipsAddressBook.json
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/EditInternshipDescriptorTest.java
- src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
- src/test/java/seedu/address/model/internship/InternshipTest.java
- src/test/java/seedu/address/storage/JsonAdaptedInternshipTest.java
- src/test/java/seedu/address/testutil/EditInternshipDescriptorBuilder.java
- src/test/java/seedu/address/testutil/InternshipBuilder.java
- src/test/java/seedu/address/testutil/InternshipUtil.java
- src/test/java/seedu/address/testutil/TypicalInternships.java
The address book is built on the Person object and its attributes, and does not have the Status field.
It is not applicable to the updated product, which is an internship application tracker which needs to show status of internship.
Let's create a Status field, and update related classes, fields, and methods to show the internship status.
Note: the current iteration does not check whether the parameter for Status is Offered, Progress, or Accepted. Will need to update soon.
> Add Status

- src/main/java/seedu/intrack/ui/InternshipCard.java
- src/main/resources/view/DarkTheme.css
The status currently shows as green no matter the status.
Colour-coding the status label will help to clearly display the application's progress.
Let's format the status label to change colour depending on the status.
> Update Status display

- src/main/java/seedu/intrack/ui/InternshipCard.java
Status appears twice in program. This is unnecessary and distracting.
Let's remove one of the statuses to clean up the UI.
> Fix status view

- src/main/java/seedu/intrack/storage/JsonAdaptedTask.java
- src/test/java/seedu/intrack/storage/JsonAdaptedTaskTest.java
Currently, there are no test cases of ```JsonAdaptedTask```. Let's add more test cases to improve the code coverage.
> Add JsonAdaptedTaskTest

- src/main/java/seedu/intrack/logic/parser/AddCommandParser.java
- src/main/java/seedu/intrack/model/internship/Task.java
- src/main/java/seedu/intrack/model/internship/Website.java
- src/main/java/seedu/intrack/ui/MainWindow.java
- src/main/java/seedu/intrack/ui/SelectedInternshipCard.java
- src/main/java/seedu/intrack/ui/UpcomingTaskCard.java
- src/main/java/seedu/intrack/ui/UpcomingTaskPanel.java
- src/main/resources/view/DarkTheme.css
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/UpcomingTaskCard.fxml
- src/main/resources/view/UpcomingTaskPanel.fxml
- src/test/java/seedu/intrack/testutil/InternshipBuilder.java
- src/test/java/seedu/intrack/testutil/TypicalInternships.java
Currently, ```InTrack``` provides a ```Task``` class with its own defined properties. Let's update the following:
* ```Task``` does not have a default value, and the ```Internship``` starts with an empty list
* The ```Task```s that have passed are not shown in the UI
* The UI now has a panel that displays the most recent upcoming ```Task```
> Update task and its UI

- docs/UserGuide.md
- src/main/java/seedu/intrack/logic/commands/SortCommand.java
- src/main/java/seedu/intrack/model/internship/Internship.java
- src/main/java/seedu/intrack/model/internship/UniqueInternshipList.java
Added exception handling for when tasks lists is empty and also updated DG
> Update UG and minor error fix for SortCommand

- src/main/java/seedu/intrack/ui/HelpWindow.java
- src/main/resources/view/HelpWindow.css
- src/main/resources/view/HelpWindow.fxml
The Help window only provides a link to the User Guide URL.
Having some common command suggestions in the Help window may help users easily and quickly find certain commands.
Let's add a section for suggested commands.
> Add command suggestions to Help window

- src/main/java/seedu/intrack/ui/HelpWindow.java
- src/main/resources/view/HelpWindow.css
- src/main/resources/view/HelpWindow.fxml
Only a few selected commands are shown in the HelpWindow.
Let's provide a more comprehensive list and change the UI.
> Change UI of HelpWindow

- docs/index.md
```index.md``` currently refers to addressbook, which will be displayed in the website. Let's change it to InTrack to become more relevant to our application.
> Rename addressbook to InTrack in ```index.md```

- docs/UserGuide.md
> Fix Issue 163

- docs/UserGuide.md
The commands in the User Guide do not really follow a logical order.
Let's section them off and restructure them to improve coherency.
> Fix organisation of User Guide

- docs/team/johnrhimawan.md
Currently, the PPP for johnrhimawan has not been updated. Let's update the PPP.
> Update PPP for John

- docs/DeveloperGuide.md
- docs/team/jetlfj.md
> Update DG use cases

- src/main/java/seedu/intrack/logic/commands/AddTaskCommand.java
- src/main/java/seedu/intrack/logic/commands/DeleteCommand.java
- src/main/java/seedu/intrack/logic/parser/AddTaskCommandParser.java
- src/main/java/seedu/intrack/logic/parser/DeleteCommandParser.java
Currently, some of the commands in InTrack do not use assertions. Let's add assertions to the code.
> Add assertions

- docs/DeveloperGuide.md
Currently, some references in the developer guide are still targeted to address book. Let's change it to the ones relevant to InTrack.
> Fix name errors

- docs/DeveloperGuide.md
Currently, the use case for mail is not added in the DG. Let's add the use case to send an email.
> Update use case for mail

- docs/UserGuide.md
Let's add more FAQs in the user guide to accommodate users' questions.
> Update FAQ in user guide

- src/test/java/seedu/intrack/logic/parser/AddTagCommandParserTest.java
- src/test/java/seedu/intrack/logic/parser/InTrackParserTest.java
- src/test/java/seedu/intrack/model/internship/InternshipTest.java
- src/test/java/seedu/intrack/testutil/InternshipUtil.java
> Add testing

- docs/DeveloperGuide.md
Currently, the developer guide does not include acknowledgements.
Let's add them to make the developer guide complete
> Add acknowledgements

- docs/UserGuide.md
CS2101 requires a user guide, let's edit the user guide to be more reader-friendly.
> [CS2101] Update User Guide
